const state = {
    userid:null,
    userInfo:null,
    danceSortList:null,
    hotArticleList:null,
    newArticleList:null,
    hotVideoList:null,
    newVideoList:null,
    messageList:null,
    articleList:[],
    videoList:[],
    noticeList:[],
    videoCollectList:[],
    articleCollectList:[],
    rotationImgList:null,
    videoResult:null,
    articleResult:null,
    token:null,
    isLogin:null,
    matchList:[],
    announcementList:[],
    keyword:'',
    roomList:[]
}
export default state;